root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/gozen.exe ./src/cmd/server/main.go"  # Changed path
  bin = "tmp/gozen.exe"  # Changed binary name
  include_ext = ["go", "yaml", "yml"]
  exclude_dir = ["vendor", "tmp", "docs"]
  delay = 1000
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
