-- Migration file generated by GoZen
-- Create users table

-- Enable foreign key support (SQLite specific)
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY DEFAULT (hex(randomblob(16))),
  first_name TEXT NOT NULL CHECK(length(first_name) BETWEEN 2 AND 50),
  last_name TEXT NOT NULL CHECK(length(last_name) BETWEEN 2 AND 50),
  username TEXT NOT NULL UNIQUE CHECK(length(username) BETWEEN 3 AND 30),
  role TEXT NOT NULL CHECK(role IN ('admin', 'user', 'manager')),
  email TEXT NOT NULL UNIQUE,
  phone TEXT NOT NULL CHECK(
    length(phone) BETWEEN 10 AND 15 AND 
    (phone LIKE '+%' OR phone GLOB '[0-9]*')
  ),
  avatar TEXT NOT NULL DEFAULT 'https://res.cloudinary.com/cloud-alpha/image/upload/v1739464346/Tours/user_oxe2tu.png'
    CHECK(avatar LIKE 'http://%' OR avatar LIKE 'https://%'),
  password TEXT NOT NULL CHECK(length(password) >= 8),
  is_active BOOLEAN DEFAULT TRUE,
  is_verified BOOLEAN DEFAULT FALSE,
  last_login_at DATETIME,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at DATETIME
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
CREATE INDEX IF NOT EXISTS idx_users_is_active ON users(is_active);
CREATE INDEX IF NOT EXISTS idx_users_deleted_at ON users(deleted_at);

-- Create trigger to automatically update updated_at column
CREATE TRIGGER IF NOT EXISTS update_users_updated_at
  AFTER UPDATE ON users
  FOR EACH ROW
  WHEN NEW.updated_at = OLD.updated_at
BEGIN
  UPDATE users SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;